### ISSUE TITLE
[run_expression_alignment_TCGADEPMAP.R] "subtype" and "Primary/Metastasis" columns missing from metadata_cellline.csv file

### ISSUE THREAD

**Issue by aambioinfo** [xushiabbvie/TCGADEPMAP#2]
Thank you for developing this very useful tool and congratulations for your fantastic publication in Nature Cancer.

In `run_expression_alignment_TCGADEPMAP.R`, "`src/metadata_cellline.csv`" is used as input for the annotation_file argument. However, this file does not contain the "`subtype`" and "`Primary/Metastasis`" columns that are supposed to be selected in a subsequent step in the script (these columns are present in the "`Celligner_info.csv`" file that can be downloaded from https://figshare.com/articles/Celligner_data/11965269, though).

Is "`src/metadata_cellline.csv`" the right file to be used as input?

Many thanks.

**Comment by xushiabbvie** [comment]
Thank you for your interest in our research. We only used "lineage" column as the cancer types. The "subtype" and "Primary/Metastasis" columns are not necessary for the analysis, which are mostly for the visualization. The code should run without issues using "src/metadata_cellline.csv". If you would like to see the UMAP plot colored by more details cancer types as subtype, you may use the "Celligner_info.csv" file as you mentioned. But there will be a few cell lines missing since that file is an older version of DepMap release. Thanks.

**Comment by aambioinfo** [comment]
Thank you for your prompt reply!
