### ISSUE TITLE
Not fully able to replicate TCGA_essentiality_scores.rds output

### ISSUE THREAD

**Issue by aambioinfo** [xushiabbvie/TCGADEPMAP#4]
Hello again, 
I have run both the `run_expression_alignment_TCGADEPMAP.R` and `build_model_predict_TCGADEPMAP.R` scripts, but the values in the `TCGA_essentiality_scores.rds` that I have obtained are a bit different to the ones published in https://figshare.com/articles/dataset/TCGADEPMAP_gene_essentiality_scores/21382011?file=41467224.
Could you please let me know if besides these 2 scripts you run any other that might explain the differences in the output? And which version of `CCLE_expression_full.csv` did you use? Could you confirm that the `Achilles_gene_effect.csv` version used if from 21Q1?
Many thanks!

**Comment by xushiabbvie** [comment]
Thank you for trying our code. I think it is normal to see some differences across different runs. The reason is there are a few steps using random seeds for initialization. For example, the cross-validation training can be slightly different if you run twice. For this project, we are more identifying the trend instead of actual values. Hope this helps.
